# .circleci/config.yml
version: 2.1

orbs:
  macos: circleci/macos@2

jobs:
  build-and-push:
    working_directory: ~/project
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      - macos/switch-ruby:
          version: "2.7.6"
      - run: cd ios
      - run: bundle install
      - run: bundle exec fastlane publish

workflows:
  push-to-testflight:
    jobs:
      - build-and-push:
          filters:
            branches:
              only: circleci-project-setup
