# .circleci/config.yml
version: 2.1
jobs:
  build-and-push:
    working_directory: ~/project
    macos:
      xcode: 14.2.0
    steps:
      - checkout

      - run: rbenv install 2.7.6
      - run: rbenv local 2.7.6
      - run: ruby --version
      - run: gem install bundler:2.3.25

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: npm install

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - restore_cache:
          key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}

      - restore_cache:
          key: pods-v1-{{ checksum "ios/Podfile.lock" }}-{{ arch }}

      - run: 
          command: bundle check || bundle install --path vendor/bundle --clean

      - run: 
          command: bundle exec pod install
          working_directory: ios

      - save_cache:
          key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle

      - save_cache:
          key: pods-v1-{{ checksum "ios/Podfile.lock" }}-{{ arch }}
          paths:
            - ios/Pods

      - run: bundle exec fastlane publish

workflows:
  push-to-testflight:
    jobs:
      - build-and-push:
          filters:
            branches:
              only: circleci-project-setup
