# .circleci/config.yml
version: 2.1
jobs:
  build-and-push:
    working_directory: ~/project
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      - run: rbenv global 3.1.3 && rbenv rehash
      - run: cd ios
      - run: bundle install
      - run: bundle exec fastlane publish

workflows:
  push-to-testflight:
    jobs:
      - build-and-push:
          filters:
            branches:
              only: circleci-project-setup
