# .circleci/config.yml
version: 2.1
jobs:
  build-and-push:
    working_directory: ~/project/ios
    macos:
      xcode: 14.2.0
    steps:
      - run: bundle exec fastlane publish

workflows:
  push-to-testflight:
    jobs:
      - build-and-push:
          filters:
            branches:
              only: circleci-project-setup
