# .circleci/config.yml
version: 2.1
jobs:
  adhoc:
    macos:
      xcode: 14.2.0
    steps:
      # ...
      - run: bundle exec fastlane publish

workflows:
  push-to-testflight:
    jobs:
      - adhoc:
          filters:
            branches:
              only: circleci-project-setup
