# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Push a new beta build to TestFlight"
  lane :publish do
    match(type: "appstore")
    gym(scheme: 'Hyperlocal', 
        workspace: './ios/Hyperlocal.xcworkspace',
        export_method: "app-store")
    
    app_store_connect_api_key
    pilot(
      distribute_external: false,
    )
  end
end
