# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Push a new beta build to TestFlight"
  lane :publish do
    # Login to App Store Connect
    app_store_connect_api_key

    # Get the version number from the project and check against
    # the latest build already available on App Store Connect, then
    # increase the build number by 1. If no build is available
    # for that version, then start at 1
    increment_build_number(
      build_number: app_store_build_number(
        initial_build_number: 1,
        version: get_version_number(xcodeproj: "ios/Hyperlocal.xcodeproj"),
        live: false
      ) + 1,
    )

    match(type: "appstore")
    gym(scheme: 'Hyperlocal', 
        workspace: './ios/Hyperlocal.xcworkspace',
        export_method: "app-store")
    
    app_store_connect_api_key
    pilot(
      distribute_external: false,
    )
  end
end
